image: ubuntu:18.04
pipelines:
  default:
    - step:
        script:
          - ./install.sh -n
          - ./pluma.py check -c pluma.yml.sample -t pluma-target.yml.sample
          - export PLUMA_ENV=CI
          - make test